# This stack saves to /home/user/docker/zeek - this can be changed by the user,
# as long as it is consistent!
# In order for this script to function properly, the folder permissions need to
# be set to 766 - otherwise the container won't be able to have write access!

# PLEASE DON'T RUN THIS SCRIPT WITHOUT ANY ACCESS CONTROL AS IT ENABLES
# ACCESS TO YOUR LOCAL DIRECTORIES THROUGH DOCKER!!!
# BEST PRACTICE WOULD BE USING A REVERSE PROXY INSTEAD OF FORWARDING THE 80 PORT!

# Before deploying, either change the /home/user/docker/zeek folder to a
# custom location, or change user to your own username.
# Make sure the permissions are set before launching
services:
  zeek:
    image: zeek/zeek:latest
    volumes:
      - /home/user/docker/zeek/zeek-logs:/zeek-logs
      - /home/user/docker/zeek/uploads:/uploads:ro
    working_dir: /zeek-logs
    user: "root"
    command: tail -f /dev/null
    restart: always

  webserver:
    image: nginx:latest
    volumes:
      - /home/user/docker/zeek/uploads:/usr/share/nginx/html/uploads
      - /home/user/docker/zeek/zipped-logs:/usr/share/nginx/html/zipped-logs:ro
      - /home/user/docker/zeek/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/user/docker/zeek/nginx/upload.php:/usr/share/nginx/html/upload.php:ro
    ports:
      - "9005:80"
    restart: always
    networks:
      - zeek

  php:
    image: php:7.4-fpm
    volumes:
      - /home/user/docker/zeek/uploads:/usr/share/nginx/html/uploads
      - /home/user/docker/zeek/zipped-logs:/usr/share/nginx/html/zipped-logs
      - /home/user/docker/zeek/nginx/upload.php:/usr/share/nginx/html/upload.php:ro
      - /home/user/docker/zeek/nginx/php.ini:/usr/local/etc/php/php.ini:ro
    restart: always
    networks:
      - zeek

  zeek_manager:
    image: debian:latest
    volumes:
      - /home/user/docker/zeek/uploads:/uploads
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/docker/zeek/scripts:/scripts
      - /home/user/docker/zeek/zeek-logs:/zeek-logs
      - /home/user/docker/zeek/zipped-logs:/zipped-logs
      - /home/user/docker/zeek/scripts/zeek_manager.sh:/zeek_manager.sh:ro
    depends_on:
      zeek:
        condition: service_started
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: ["/bin/bash", "/zeek_manager.sh"]
    restart: always

networks:
  zeek:
    external: false
