name: Build Release Binaries

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output_name: Linux
          - os: windows-latest
            output_name: Windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build Framework-dependent
      run: dotnet build --configuration Release --no-restore

    - name: Publish Framework-dependent
      run: dotnet publish -c Release -o ./publish-fd

    - name: Build Self-contained
      run: dotnet publish -c Release -r ${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || 'win-x64' }} --self-contained true -p:PublishSingleFile=true -o ./publish-sc

    - name: Upload Framework-dependent Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output_name }}-Framework-dependent
        path: ./publish-fd

    - name: Upload Self-contained Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output_name }}-Self-contained
        path: ./publish-sc
