name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Get version
      id: get_version
      run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

    - name: Build for Linux
      run: |
        dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./linux-sc
        dotnet publish -c Release -r linux-x64 -o ./linux-fd

    - name: Build for Windows
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./windows-sc
        dotnet publish -c Release -r win-x64 -o ./windows-fd

    - name: Zip builds
      run: |
        zip -r Linux-Self-contained.zip ./linux-sc
        zip -r Linux-Framework-dependent.zip ./linux-fd
        zip -r Windows-Self-contained.zip ./windows-sc
        zip -r Windows-Framework-dependent.zip ./windows-fd

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Linux Self-contained
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Linux-Self-contained.zip
        asset_name: Linux-Self-contained.zip
        asset_content_type: application/zip

    - name: Upload Linux Framework-dependent
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Linux-Framework-dependent.zip
        asset_name: Linux-Framework-dependent.zip
        asset_content_type: application/zip

    - name: Upload Windows Self-contained
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Windows-Self-contained.zip
        asset_name: Windows-Self-contained.zip
        asset_content_type: application/zip

    - name: Upload Windows Framework-dependent
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Windows-Framework-dependent.zip
        asset_name: Windows-Framework-dependent.zip
        asset_content_type: application/zip

    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
